<a href="https://colab.research.google.com/github/Tensor-Reloaded/Neural-Networks-Template-2024/blob/main/Lab01/GS-Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python fundamentals

### Data types

In [1]:
a = 5
print(type(a))

<class 'int'>


In [2]:
a = 5.0
print(type(a))

<class 'float'>


In [3]:
a = "5"
print(type(a))

<class 'str'>


In [4]:
a = True
print(type(a))

<class 'bool'>


## Containers

In [5]:
a_list = [1, 2, 2, 3.0, "5"]
print(a_list)
print(type(a_list))

[1, 2, 2, 3.0, '5']
<class 'list'>


In [6]:
a_set = set(a_list)
print(a_set)
print(type(a_set))
a_set = {1, 2, 3, 4}
print(a_set)

{1, 2, 3.0, '5'}
<class 'set'>
{1, 2, 3, 4}


In [7]:
a_dict = {1: "unu", "doi": 2, 3.0: a_set}
print("Keys:\t", list(a_dict.keys()))
print("Values:\t", list(a_dict.values()))
print(a_dict)
print(type(a_dict))

Keys:	 [1, 'doi', 3.0]
Values:	 ['unu', 2, {1, 2, 3, 4}]
{1: 'unu', 'doi': 2, 3.0: {1, 2, 3, 4}}
<class 'dict'>


## Functions

In [8]:
def add_two_values(a, b):
    return a + b


add_two_values(5, 6)

11

In [9]:
def multiply(a: float, b: float) -> float:
    return a * b


multiply(4.0, 5.0)

20.0

In [10]:
multiply("AB", 2)

'ABAB'

# Numpy

Check: https://numpy.org/doc/stable/user/absolute_beginners.html

### Installing 3rd party libraries

In [11]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
%pip install timed-decorator

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [13]:
import numpy as np
from math import sqrt
from timed_decorator.simple_timed import timed

In [14]:
x = np.random.uniform(low=-5.5, high=5.5, size=(50,))
x

array([-3.35579265,  0.9546352 ,  0.62177839, -4.57735193, -0.51455709,
       -1.67000769,  0.25687889, -2.56172292, -0.98765471,  2.98705161,
       -2.96813261, -1.45973576,  0.36777996,  1.82298512,  0.5594974 ,
        2.32583209,  2.31792878,  3.09000088, -4.16908648,  1.74728546,
       -2.11932325, -0.56272698,  3.446967  , -3.20110322,  1.99524309,
       -4.2897601 , -5.38319427, -1.11098571,  0.38073034,  2.08097408,
       -2.75541836,  4.80440841, -3.67410616,  0.48309542, -4.44998223,
       -4.18441979, -3.02821234, -2.15552277, -2.58141178, -2.26091427,
        3.86337934, -0.5498615 ,  1.96897831,  5.20548486,  0.12164991,
        3.90537372, -1.3218358 ,  1.90856075,  0.48377455, -1.83792733])

In [15]:
x > 0

array([False,  True,  True, False, False, False,  True, False, False,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True, False, False,  True, False,  True, False, False,
       False,  True,  True, False,  True, False,  True, False, False,
       False, False, False, False,  True, False,  True,  True,  True,
        True, False,  True,  True, False])

In [16]:
x[x > 0]

array([0.9546352 , 0.62177839, 0.25687889, 2.98705161, 0.36777996,
       1.82298512, 0.5594974 , 2.32583209, 2.31792878, 3.09000088,
       1.74728546, 3.446967  , 1.99524309, 0.38073034, 2.08097408,
       4.80440841, 0.48309542, 3.86337934, 1.96897831, 5.20548486,
       0.12164991, 3.90537372, 1.90856075, 0.48377455])

In [17]:
list(x)

[-3.355792651051157,
 0.9546351984328503,
 0.6217783948513116,
 -4.577351929334227,
 -0.5145570930779275,
 -1.6700076935945352,
 0.25687888812815896,
 -2.5617229150577074,
 -0.9876547111933132,
 2.987051609089068,
 -2.9681326108151813,
 -1.4597357610489112,
 0.367779961996888,
 1.8229851200774023,
 0.5594974039788383,
 2.325832086168628,
 2.3179287794082386,
 3.0900008780995876,
 -4.16908647995641,
 1.7472854638369437,
 -2.119323248372832,
 -0.56272698314298,
 3.446966997383557,
 -3.2011032208449857,
 1.9952430850875755,
 -4.289760102008439,
 -5.383194266152336,
 -1.110985705866593,
 0.38073034237539805,
 2.080974077052087,
 -2.7554183639439467,
 4.8044084125958335,
 -3.6741061605940804,
 0.4830954232985718,
 -4.449982226104304,
 -4.1844197936848495,
 -3.028212342580002,
 -2.1555227744658954,
 -2.581411781064231,
 -2.2609142714749613,
 3.86337933689099,
 -0.549861499195238,
 1.9689783059153783,
 5.2054848551501,
 0.1216499104509472,
 3.9053737243673616,
 -1.3218358009231412,
 1.9085607

## Comparing numpy arrays to python lists

In [18]:
@timed(show_args=True, use_seconds=True)
def normalize_np(x: np.ndarray) -> np.ndarray:
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std


@timed(show_args=True, use_seconds=True)
def normalize_py(x: list) -> list:
    mean = sum(x) / len(x)
    var = sum([(i - mean) ** 2 for i in x]) / len(x)
    std = sqrt(var)
    return [(i - mean) / std for i in x]


x = np.random.uniform(low=-5.5, high=5.5, size=(50000,)).astype(np.float64)
y = list(x)
normalized_x = normalize_np(x)
normalized_y = normalize_py(y)
assert np.allclose(normalized_x, normalized_y)

normalize_np(ndarray(50000,)) -> total time: 0.000481900s
normalize_py(list(float64)[50000]) -> total time: 0.015818000s


#### Python is slower than numpy in general

In [19]:
%%timeit

np.min(x)

8.37 μs ± 129 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [20]:
%%timeit

min(y)

582 μs ± 8.33 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [21]:
a = np.random.uniform(low=-5.5, high=5.5, size=(50,)).astype(np.float64)
b = list(a)

In [22]:
%%timeit

np.min(a)

2.32 μs ± 41.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [23]:
%%timeit

min(b)

653 ns ± 19.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## Inplace operations
Use them when you can safely modify the input

In [24]:
@timed(show_args=True, use_seconds=True)
def normalize_np_(x: np.ndarray) -> np.ndarray:
    mean = np.mean(x)
    std = np.std(x)
    x -= mean
    x /= std
    return x

In [25]:
x = np.random.rand(1000, 20000)

# This creates a copy
y = normalize_np(x)
assert not np.allclose(x, y)

# Inplace operations modify the original array! But they are faster and use less memory.
z = normalize_np_(x)
assert np.array_equal(x, z)

normalize_np(ndarray(1000, 20000)) -> total time: 0.184175800s
normalize_np_(ndarray(1000, 20000)) -> total time: 0.131637800s
